services:
  - type: web
    name: mediafetchr-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 20.0.0 